### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by wevve** [bnmgh1/node-sandbox#1]
window.bdms ，/* V 1.0.1.5 */
 
`报错堆栈 ->  Error: zxcasd
    at 5020 (dsadczxf.js:86829:28)
    at t (dsadczxf.js:90808:20)
    at 1844 (dsadczxf.js:86841:21)
    at t (dsadczxf.js:90808:20)
    at 2262 (dsadczxf.js:88518:21)
    at t (dsadczxf.js:90808:20)
    at 5245 (dsadczxf.js:88555:13)
    at t (dsadczxf.js:90808:20)
    at dsadczxf.js:90852:9
    at dsadczxf.js:97188:6
报错堆栈 ->  Error: a
    at dsadczxf.js:86852:25
    at e.exports (dsadczxf.js:86885:30)
    at 6051 (dsadczxf.js:86851:26)
    at t (dsadczxf.js:90808:20)
    at 1844 (dsadczxf.js:86842:21)
    at t (dsadczxf.js:90808:20)
    at 2262 (dsadczxf.js:88518:21)
    at t (dsadczxf.js:90808:20)
    at 5245 (dsadczxf.js:88555:13)
    at t (dsadczxf.js:90808:20)

#
# Fatal error in , line 0
# Check failed: (location_) != nullptr.
#
#
#
#FailureMessage Object: 00000077B0DFC500
 1: 00007FF788044BEF v8_inspector::V8StackTrace::V8StackTrace+4159049
 2: 00007FF787EF259F v8_inspector::V8StackTrace::V8StackTrace+2772985
 3: 00007FF789AC1062 v8_inspector::V8StackTrace::V8StackTrace+31931068
 4: 00007FF788DE6842 v8_inspector::V8StackTrace::V8StackTrace+18453148
 5: 00007FF7894542B6 v8_inspector::V8StackTrace::V8StackTrace+25193744
 6: 00007FF7889FF698 v8_inspector::V8StackTrace::V8StackTrace+14360818
 7: 00007FF7889FF1F2 v8_inspector::V8StackTrace::V8StackTrace+14359628
 8: 00007FF788CA4487 v8_inspector::V8StackTrace::V8StackTrace+17133281
 9: 00007FF788CA945F v8_inspector::V8StackTrace::V8StackTrace+17153721
10: 00007FF7895EFB81 v8_inspector::V8StackTrace::V8StackTrace+26879451
11: 00007FF789692B9A v8_inspector::V8StackTrace::V8StackTrace+27547124
12: 00007FF7894F0DE0 v8_inspector::V8StackTrace::V8StackTrace+25835578
13: 00007FF7894F0DE0 v8_inspector::V8StackTrace::V8StackTrace+25835578
14: 00007FF7894F0DE0 v8_inspector::V8StackTrace::V8StackTrace+25835578
15: 00007FF709983F84`

**Comment by bnmgh1** [comment]
你这个日志不全，应该是node底层找不到js框架里的函数导致的报错... 比如Document.get_cookie、Document_createElement

**Comment by bnmgh1** [comment]
这个框架很多优化没做好，可以看新开源的

**Comment by wevve** [comment]
谢谢老大，我研究下新的
